[package]
name = "numberpad_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = "0.12.1"
lazy_static = "1.4.0"
uinput = "0.1.3"
